
jobs:
  include:
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install build-essential libboost-all-dev xsltproc gcc-7 autorevision
        - eval "${MATRIX_EVAL}"
      compiler:
        - gcc
      script: mkdir build && cd build && cmake .. && make -j4 && ctest -V 

    - language: nix
      before_install:
        - cd nixos
      script: 
        - nix-build 

